services:
  mariadb:
    build: #how to build a custom image (Dockerfile)
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always #restarts automatically in case of crash
    env_file:
      - .env #the container will have the env vars defined in this file
    secrets:  #securely pass sensitive info to the container (will not be found as an env)
      - mariadb_root_password
      - mariadb_user_password
    ports: #ports open for the container
      - "3306:3306"
    networks: #custom network for the containers to communicate securely
      - inception_net
    volumes: #physical storage is at home/data/mariadb, the name of that storage is mariadb_data. Internally, the path is /var/lib/mysql
      - mariadb_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
      - wp_admin_password
      - wp_user_password
    ports:
      - "9000:9000"
    networks:
      - inception_net
    volumes:
       - wordpress_data:/var/www/html

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
       - wordpress_data:/var/www/html

volumes: #store data on host
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts: #bind mount, "this directory should be available inside the container as a volume"
      type: none #use my existing host folder home/data/mariadb, not something else
      device: ${HOME}/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind


secrets:
  mariadb_root_password:
    file: ./../secrets/mariadb_root_password.txt
  mariadb_user_password:
    file: ./../secrets/mariadb_user_password.txt
  wp_admin_password:
    file: ./../secrets/wp_admin_password.txt
  wp_user_password:
    file: ./../secrets/wp_user_password.txt

networks:
  inception_net:
    name: inception_net
    driver: bridge #private internal network