services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - root_password
      - user_password
    ports:
      - "3306:3306"
    networks:
      - inception_net
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    secrets:
      - root_password
      - user_password
    ports:
      - "9000:9000"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    name: mariadb_data
  wordpress_data:
    name: wordpress_data

secrets:
  root_password:
    file: ./../secrets/root_password.txt
  user_password:
    file: ./../secrets/user_password.txt

networks:
  inception_net:
    name: inception_net
    driver: bridge
